from __future__ import annotations

from typing import Protocol

from devops_agent.domain.models import (
    AgentSpace,
    ChatMessage,
    Investigation,
    JournalRecord,
    McpServer,
    Recommendation,
    Runbook,
    Skill,
    TopologyEdge,
    TopologyNode,
)


class Store(Protocol):
    def put_agent_space(self, space: AgentSpace) -> AgentSpace: ...
    def get_agent_space(self, space_id: str) -> AgentSpace | None: ...
    def list_agent_spaces(self) -> list[AgentSpace]: ...
    def delete_agent_space(self, space_id: str) -> None: ...

    def put_investigation(self, inv: Investigation) -> Investigation: ...
    def get_investigation(self, inv_id: str) -> Investigation | None: ...
    def list_investigations(self, space_id: str | None = None) -> list[Investigation]: ...

    def append_journal(self, record: JournalRecord) -> JournalRecord: ...
    def list_journal(self, investigation_id: str, after_id: str | None = None) -> list[JournalRecord]: ...

    def put_skill(self, skill: Skill) -> Skill: ...
    def list_skills(self, space_id: str) -> list[Skill]: ...

    def put_runbook(self, runbook: Runbook) -> Runbook: ...
    def get_runbook(self, runbook_id: str) -> Runbook | None: ...
    def list_runbooks(self, space_id: str | None = None) -> list[Runbook]: ...

    def put_mcp(self, server: McpServer) -> McpServer: ...
    def get_mcp(self, server_id: str) -> McpServer | None: ...
    def list_mcp(self) -> list[McpServer]: ...

    def put_node(self, node: TopologyNode) -> TopologyNode: ...
    def put_edge(self, edge: TopologyEdge) -> TopologyEdge: ...
    def list_nodes(self, space_id: str) -> list[TopologyNode]: ...
    def list_edges(self, space_id: str) -> list[TopologyEdge]: ...
    def get_node(self, node_id: str) -> TopologyNode | None: ...

    def put_recommendation(self, rec: Recommendation) -> Recommendation: ...
    def list_recommendations(self, space_id: str | None = None) -> list[Recommendation]: ...
    def get_recommendation(self, rec_id: str) -> Recommendation | None: ...

    def put_chat(self, msg: ChatMessage) -> ChatMessage: ...
    def list_chat(self, investigation_id: str) -> list[ChatMessage]: ...
